#Server port
server:
  port: 11405
  
spring:
  application:
    name: config-server 
 
#Git repo location 

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fiazz/config-server-repo
          searchPaths: '{application}'
 
